name: Build and Push Docker Compose Services

on:
  push:
    branches:
      - main  # or master, or any branch you prefer

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Compose Images
      run: |
        touch .env
        docker compose build
        docker compose push